version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    networks:
      - app-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
