version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/ET-App
      - public-data:/ET-App/public
      - tmp-data:/ET-App/tmp
      - log-data:/ET-App/log
    networks:
      - app-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/ET-App/public
      - tmp-data:/ET-App/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  app-network:
    external: true
