version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/ET-App
    steps:
      - checkout:
          path: ~/ET-App
      - ruby/install-deps
  test:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/ET-App
    steps:
      - checkout:
          path: ~/ET-App
      - ruby/install-deps
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build